// Compile the TypeScript sources into a deployable Catalyst function tree.
//
// The sources are ESM TypeScript with explicit `.ts` import specifiers, which is
// what lets `node --test` run them with no build step at all during development.
// The Catalyst node18 stack is CommonJS and has no TypeScript support, so the
// deploy tree is compiled: `module: commonjs` plus
// `rewriteRelativeImportExtensions`, which turns `./x.ts` into `require('./x.js')`.
//
// Everything under catalyst/deploy is generated. Gitignored, never edited,
// always overwritten. Source of truth is functions/ and shared/.
//
// Usage:
//   node catalyst/tools/build-functions.ts
//   node catalyst/tools/build-functions.ts --check   (verify it compiles, emit nothing)

import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, '..', '..');
export const DEPLOY_DIR = join(REPO_ROOT, 'catalyst', 'deploy');
export const FUNCTION_NAME = 'coordination';

/**
 * Every function this build deploys.
 *
 * `advancedio` for the request routes, because only Advanced I/O hands a handler
 * the raw request bytes the webhook HMAC needs. `cron` for the reaper, which has
 * no caller and runs on a schedule.
 *
 * Both directories get their OWN compiled copy of the shared code: Catalyst
 * deploys each function independently, so a cross-directory require would resolve
 * locally and fail only once deployed.
 */
export const TARGETS: { name: string; type: 'advancedio' | 'job'; entry: string }[] = [
  { name: 'coordination', type: 'advancedio', entry: 'functions/coordination/index.js' },
  // JOB, not CRON. The build order says "Cron Function", and a cron-type function
  // turned out to be unreachable programmatically: HTTP invocation returns 403
  // "HTTP Execution is not supported", local `functions:execute` needs a node18
  // binary, and the Job Scheduling API refuses it with "The given function is not
  // a job function." A job-type function is schedulable AND triggerable on
  // demand through the same API, so it is the reaper that can actually be tested.
  { name: 'reaper', type: 'job', entry: 'functions/reaper/index.js' },
];

/** The compiler options the deploy tree needs, as a tsconfig written on the fly. */
export function buildTsconfig(outDir: string): unknown {
  return {
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2022'],
      // CommonJS: the node18 stack's entry contract is `module.exports = fn`.
      module: 'commonjs',
      moduleResolution: 'node',
      types: ['node'],
      strict: true,
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      // Turns './x.ts' in the source into require('./x.js') in the output. Without
      // it every emitted require points at a file that does not exist, and the
      // failure appears only when the deployed function is first invoked.
      rewriteRelativeImportExtensions: true,
      esModuleInterop: true,
      outDir,
      noEmit: false,
      declaration: false,
      sourceMap: false,
    },
    // Tests are not deployed. Nor are the tools, which use import.meta.url and
    // would not survive the CommonJS transform.
    include: ['functions/**/*.ts', 'shared/**/*.ts', 'catalyst/lib/**/*.ts', 'catalyst/schema/**/*.ts'],
    exclude: ['**/*.test.ts', 'catalyst/tools/**', 'catalyst/testing/**', 'catalyst/deploy/**'],
  };
}

/**
 * The entry point Catalyst invokes.
 *
 * Kept as hand-written CommonJS rather than compiled from TypeScript, because it
 * is the one file whose exact shape the platform dictates: `module.exports` must
 * be the `(req, res)` handler itself.
 */
/**
 * The Advanced I/O entry point Catalyst invokes.
 *
 * Hand-written CommonJS rather than compiled from TypeScript, because it is the
 * one file whose exact shape the platform dictates: `module.exports` must be the
 * `(req, res)` handler itself.
 */
const ENTRY_ADVANCEDIO = `'use strict';
// GENERATED by catalyst/tools/build-functions.ts -- do not edit.
const catalyst = require('zcatalyst-sdk-node');
const { serve } = require('./dist/functions/coordination/index.js');

module.exports = async (req, res) => {
  // initialize(req) binds the SDK to this invocation's credentials and project.
  const app = catalyst.initialize(req);
  try {
    await serve(app, req, res);
  } catch (err) {
    // Last resort. serve() maps its own errors; anything reaching here is a bug
    // in the wiring, and an Advanced I/O function that never writes a response
    // is silently terminated at the 30 s cap with no log line.
    console.error(JSON.stringify({
      level: 'error', code: 'function.unhandled',
      message: err && err.message ? err.message : String(err),
      stack: err && err.stack ? err.stack : undefined,
    }));
    if (!res.headersSent) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.write(JSON.stringify({ error: 'internal', code: 'UNHANDLED' }));
    }
    res.end();
  }
};
`;

/**
 * The Job entry point.
 *
 * A job handler receives (jobRequest, context) and MUST call
 * context.closeWithSuccess() or closeWithFailure(). Failing to close leaves the
 * execution hanging until the cap, where it is silently terminated with no log
 * line saying why -- so both paths close explicitly.
 */
const ENTRY_JOB = `'use strict';
// GENERATED by catalyst/tools/build-functions.ts -- do not edit.
const catalyst = require('zcatalyst-sdk-node');
const { reap } = require('./dist/functions/reaper/index.js');
const { consoleLogger } = require('./dist/shared/log.js');

module.exports = async (jobRequest, context) => {
  // initialize(CONTEXT), not initialize(jobRequest) and not initializeApp().
  //
  // The job handler receives two parameters and only the SECOND one can
  // initialize the SDK. The generated types say so outright: Context is
  // "the object used to initialize the Catalyst sdk" and carries
  // catalystHeaders, which is exactly what the SDK's basicio branch reads
  // (see catalyst-namespace.js). jobRequest carries only getters and has
  // neither headers nor catalystHeaders, so initialize(jobRequest) throws
  // invalid_app_object.
  //
  // Both wrong forms fail identically: job_status FAILURE with response_code
  // "Code_Exception", no message, and NOTHING retrievable from the logs API.
  // Two deploy cycles were spent distinguishing them.
  const app = catalyst.initialize(context);
  try {
    const result = await reap(app, consoleLogger);
    context.closeWithSuccess(JSON.stringify(result));
  } catch (err) {
    console.error(JSON.stringify({
      level: 'error', code: 'job.unhandled',
      message: err && err.message ? err.message : String(err),
      stack: err && err.stack ? err.stack : undefined,
    }));
    context.closeWithFailure();
  }
};
`;

function entryFor(type: 'advancedio' | 'job'): string {
  return type === 'job' ? ENTRY_JOB : ENTRY_ADVANCEDIO;
}

export function build(opts: { check?: boolean } = {}): { targets: string[] } {
  if (opts.check !== true) {
    rmSync(join(DEPLOY_DIR, 'functions'), { recursive: true, force: true });
  }

  // Compile once per target, into that target's own dist/. Catalyst deploys each
  // function directory independently, so they cannot share one build output.
  for (const target of TARGETS) {
    const functionDir = join(DEPLOY_DIR, 'functions', target.name);
    const outDir = join(functionDir, 'dist');
    if (opts.check !== true) mkdirSync(outDir, { recursive: true });

    const tsconfigPath = join(REPO_ROOT, `tsconfig.deploy.${target.name}.generated.json`);
    writeFileSync(tsconfigPath, JSON.stringify(buildTsconfig(outDir), null, 2), 'utf8');
    try {
      execFileSync('npx', ['tsc', '-p', tsconfigPath, ...(opts.check === true ? ['--noEmit'] : [])], {
        cwd: REPO_ROOT, stdio: 'inherit',
      });
    } finally {
      rmSync(tsconfigPath, { force: true });
    }

    if (opts.check === true) continue;

    writeFileSync(join(functionDir, 'index.js'), entryFor(target.type), 'utf8');

    writeFileSync(join(functionDir, 'catalyst-config.json'), `${JSON.stringify({
      deployment: {
        name: target.name,
        stack: 'node18',
        type: target.type,
        env_variables: {},
      },
      execution: { main: 'index.js' },
    }, null, 2)}\n`, 'utf8');

    writeFileSync(join(functionDir, 'package.json'), `${JSON.stringify({
      name: target.name,
      version: '1.0.0',
      main: 'index.js',
      private: true,
      dependencies: { 'zcatalyst-sdk-node': '^3.4.0' },
    }, null, 2)}\n`, 'utf8');

    // A job function has no HTTP request to carry its payload, so `catalyst
    // functions:execute` reads one from this file.
    if (target.type === 'job') {
      writeFileSync(join(functionDir, 'catalyst-inputs.json'), `${JSON.stringify({
        job_details: { job_meta_details: { params: {} } },
      }, null, 2)}\n`, 'utf8');
    }
  }

  if (opts.check !== true) {
    writeFileSync(join(DEPLOY_DIR, 'catalyst.json'), `${JSON.stringify({
      functions: { targets: TARGETS.map((t) => t.name), ignore: [], source: 'functions' },
    }, null, 2)}\n`, 'utf8');
  }

  return { targets: TARGETS.map((t) => t.name) };
}

function main(argv: string[]): number {
  const check = argv.includes('--check');
  const { targets } = build({ check });
  console.log(check ? 'deploy tree compiles' : `built ${targets.join(', ')}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
