// Compile the TypeScript sources into a deployable Catalyst function tree.
//
// The sources are ESM TypeScript with explicit `.ts` import specifiers, which is
// what lets `node --test` run them with no build step at all during development.
// The Catalyst node18 stack is CommonJS and has no TypeScript support, so the
// deploy tree is compiled: `module: commonjs` plus
// `rewriteRelativeImportExtensions`, which turns `./x.ts` into `require('./x.js')`.
//
// Everything under catalyst/deploy is generated. Gitignored, never edited,
// always overwritten. Source of truth is functions/ and shared/.
//
// Usage:
//   node catalyst/tools/build-functions.ts
//   node catalyst/tools/build-functions.ts --check   (verify it compiles, emit nothing)

import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, '..', '..');
export const DEPLOY_DIR = join(REPO_ROOT, 'catalyst', 'deploy');
export const FUNCTION_NAME = 'coordination';

/** The compiler options the deploy tree needs, as a tsconfig written on the fly. */
export function buildTsconfig(outDir: string): unknown {
  return {
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2022'],
      // CommonJS: the node18 stack's entry contract is `module.exports = fn`.
      module: 'commonjs',
      moduleResolution: 'node',
      types: ['node'],
      strict: true,
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      // Turns './x.ts' in the source into require('./x.js') in the output. Without
      // it every emitted require points at a file that does not exist, and the
      // failure appears only when the deployed function is first invoked.
      rewriteRelativeImportExtensions: true,
      esModuleInterop: true,
      outDir,
      noEmit: false,
      declaration: false,
      sourceMap: false,
    },
    // Tests are not deployed. Nor are the tools, which use import.meta.url and
    // would not survive the CommonJS transform.
    include: ['functions/**/*.ts', 'shared/**/*.ts', 'catalyst/lib/**/*.ts', 'catalyst/schema/**/*.ts'],
    exclude: ['**/*.test.ts', 'catalyst/tools/**', 'catalyst/testing/**', 'catalyst/deploy/**'],
  };
}

/**
 * The entry point Catalyst invokes.
 *
 * Kept as hand-written CommonJS rather than compiled from TypeScript, because it
 * is the one file whose exact shape the platform dictates: `module.exports` must
 * be the `(req, res)` handler itself.
 */
const ENTRY_JS = `'use strict';
// GENERATED by catalyst/tools/build-functions.ts -- do not edit.
const catalyst = require('zcatalyst-sdk-node');
const { serve } = require('./dist/functions/coordination/index.js');

module.exports = async (req, res) => {
  // initialize(req) binds the SDK to this invocation's credentials and project.
  const app = catalyst.initialize(req);
  try {
    await serve(app, req, res);
  } catch (err) {
    // Last resort. serve() maps its own errors; anything reaching here is a bug
    // in the wiring, and an Advanced I/O function that never writes a response
    // is silently terminated at the 30 s cap with no log line.
    console.error(JSON.stringify({
      level: 'error', code: 'function.unhandled',
      message: err && err.message ? err.message : String(err),
      stack: err && err.stack ? err.stack : undefined,
    }));
    if (!res.headersSent) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.write(JSON.stringify({ error: 'internal', code: 'UNHANDLED' }));
    }
    res.end();
  }
};
`;

export function build(opts: { check?: boolean } = {}): { outDir: string; functionDir: string } {
  const functionDir = join(DEPLOY_DIR, 'functions', FUNCTION_NAME);
  const outDir = join(functionDir, 'dist');

  if (opts.check !== true) {
    rmSync(join(DEPLOY_DIR, 'functions'), { recursive: true, force: true });
    mkdirSync(outDir, { recursive: true });
  }

  const tsconfigPath = join(REPO_ROOT, 'tsconfig.deploy.generated.json');
  writeFileSync(tsconfigPath, JSON.stringify(buildTsconfig(outDir), null, 2), 'utf8');

  try {
    execFileSync('npx', ['tsc', '-p', tsconfigPath, ...(opts.check === true ? ['--noEmit'] : [])], {
      cwd: REPO_ROOT, stdio: 'inherit',
    });
  } finally {
    rmSync(tsconfigPath, { force: true });
  }

  if (opts.check === true) return { outDir, functionDir };

  writeFileSync(join(functionDir, 'index.js'), ENTRY_JS, 'utf8');

  writeFileSync(join(functionDir, 'catalyst-config.json'), `${JSON.stringify({
    deployment: {
      name: FUNCTION_NAME,
      stack: 'node18',
      type: 'advancedio',
      env_variables: {},
    },
    execution: { main: 'index.js' },
  }, null, 2)}\n`, 'utf8');

  writeFileSync(join(functionDir, 'package.json'), `${JSON.stringify({
    name: FUNCTION_NAME,
    version: '1.0.0',
    main: 'index.js',
    private: true,
    dependencies: { 'zcatalyst-sdk-node': '^3.4.0' },
  }, null, 2)}\n`, 'utf8');

  writeFileSync(join(DEPLOY_DIR, 'catalyst.json'), `${JSON.stringify({
    functions: { targets: [FUNCTION_NAME], ignore: [], source: 'functions' },
  }, null, 2)}\n`, 'utf8');

  return { outDir, functionDir };
}

function main(argv: string[]): number {
  const check = argv.includes('--check');
  const { functionDir } = build({ check });
  console.log(check ? 'deploy tree compiles' : `built ${functionDir}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
